version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: eventzs_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    image: aissiez/eventzs:v1
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/eventzs_management
    networks:
      - app-network
    deploy:
      replicas: 5

networks:
  app-network:
    driver: overlay

volumes:
  postgres_data:
