name: CI/CD

on:
  push:
    branches:
      - main  # Ejecuta la acción solo en el branch 'main'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Ejecutar los tests (ajusta este comando según tu proyecto)
      # - name: Run tests
      #   run: |
      #     echo "Running tests..."
      #     # npm install
      #     # npm test

      # Log in a Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/eventzs:${{ github.sha }} .
      
      # Subir la imagen a Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/eventzs:${{ github.sha }}
